config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'welcome#index', as: "root"

  resources :users do
    resources :entries
  end
  resources :categories
  # SESSION ROUTES
  get '/login' => 'sessions#new', as: 'login'
  get '/auth/:provider/callback' => 'sessions#create_with_facebook'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  # REPORTS ROUTE
  get '/reports' => 'reports#index', as: 'reports'
  # DASHBOARD ROUTE
  get '/dashboard' => 'dashboard#index', as: 'dashboard'



end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :require_login

  def index
    @user = current_user
    @entries = @user.entries
    p "#{@entries} this is entries"
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div class="container">
    <h2>Dashboard</h2>
    <hr>
    <div class="row">
      <h4>Latest Transactions</h4>
    </div>
    <div class="row">
      <table>
          <tr>
            <th>Receipt</th>
            <th>Date</th>
            <th>Category</th>
            <th>Amount</th>
            <th>Options</th>
          </tr>
          <% latest_entries(@user.entries).each do |entry| %>
            <tr>
              <td><%= image_tag entry.receipt, class:"receipt_preview materialboxed"%></td>
              <td><%= entry.day %></td>
              <td><%= entry.category.name %></td>
              <td><%= number_to_currency(entry.amount) %></td>
              <td>
                &nbsp;<i class="material-icons">open_with</i><%= link_to "view", user_entry_path(current_user,entry), :method => :get %>
                &nbsp;<i class="material-icons">mode_edit</i><%= link_to "Edit", edit_user_entry_path(current_user,entry), :method => :get %>
                &nbsp;<i class="material-icons">delete</i><%= link_to "Delete", user_entry_path(current_user,entry), :method => :delete, data: {confirm: "Are you sure you want to delete this transaction?"} %>
              </td>
            </tr>
          <% end %>
        </table>
        <div class="row">

        </div>
        <div class="row left-align">
          <div class="col s2"></div>
          <div class="col s12 m4">
            <%= button_to "Add Transaction", new_user_entry_path(current_user), :method => :get, class:"btn btn-large" %>
          </div>
          <div class="col s12 m4">
            <%= button_to "View Categories", categories_path, :method => :get, class:"btn btn-large" %>
          </div>
        </div>