config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'welcome#index', as: "root"

  resources :users do
    resources :entries
  end
  resources :categories
  # SESSION ROUTES
  get '/login' => 'sessions#new', as: 'login'
  get '/auth/:provider/callback' => 'sessions#create_with_facebook'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  # REPORTS ROUTE
  get '/reports' => 'reports#index', as: 'reports'
  # DASHBOARD ROUTE
  get '/dashboard' => 'dashboard#index', as: 'dashboard'



end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :entries
  has_many :authorizations
  validates_uniqueness_of :username, :email
  # user.url = auth_hash['info']['urls'][user.provider.capitalize]
  include UsersHelper
  def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user.try(:authenticate, params[:password])
  end


  # def from_omniauth(auth_hash)
  #   user = find_or_create_by(uid: auth_hash['uid'], provider: auth_hash['provider'])
  #   user.name = auth_hash['info']['name']
  #   user.location = auth_hash['info']['location']
  #   user.image_url = auth_hash['info']['image']
  #   user.url = auth_hash['info']['urls']['Twitter']
  #   user.save!
  #   user
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    user = User.create(user_params)
    if user.save
      login(user)
      redirect_to user_path(user)
    else
      user.errors.full_messages.each do |message|
        flash[:error] = message
      end
      redirect_to new_user_path
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      user.errors.full_messages.each do |message|
        flash[:error] = message
      end
      redirect_to edit_user_path(@user)
    end
  end

  def destroy
    @user = User.find_by_id(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:email, :username,  :password, :name, :password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <h2>EDIT PROFILE</h2>
    <hr>
  </div>
  <div class="row">
    <%= form_for @user do |f| %>
    <div class="row">
      <div class="col-md-6">
        <%= f.label :username, required:"true" %>:
        <%= f.text_field :username, placeholder: "Username" %>
      </div>
      <div class="col-md-6">
        <%= f.label :email %>:
        <%= f.email_field :email, placeholder: "Email" %>
      </div>
    </div>
    <%= f.submit "Save", class:"btn btn-danger" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>edit this file</h1>

app/views/users/new.html.erb
<!-- SIGNUP FORM  -->
<div class="container">
    <h2 class="left-align">Let's get started!</h2>
    <hr>
    <p class="center red-text">
      <% flash.each do |name, msg| %>
      <strong><%= msg %></strong>
      <% end %>
    </p>
    <div class="col m8 offset-m2 col s12">
        <%= form_for @user  do |f| %>
        <div class="row">
            <div class="col s6">
              <%=f.label :email %>
              <%= f.text_field :email, placeholder: "e.g:yourname@example.com", class:"validate", type:"email", required: true %>
            </div>
            <div class="col s6">
              <%= f.label :username %>
              <%= f.text_field :username , class:"validate", required: true %>
            </div>
        </div>
        <div class="row">
            <div class="col s6">
              <%= f.label :password %>
              <%= f.password_field :password, placeholder: "Password", class:"validate", required: true%>
            </div>
            <div class="col s6">
              <%= f.label :password_confirmation %>
              <%= f.password_field :password_confirmation, placeholder: "Confirm Password", class:"validate", required: true%>
            </div>

        </div>
        <%= f.submit "Sign Up", class:"btn" %>
        <% end %>
    </div>
    <h2>OR</h2>
    <div class="row">
      <%= link_to "/auth/facebook", class: "" do %>
        <%= image_tag 'login-facebook.png', class:"hoverable", id:"facebook-btn" %>
      <% end %>
    </div>

</div>

app/views/users/show.html.erb
<!-- USER PROFILE PAGE  -->
<div class="container">
  <div class="row">
    <h2>Welcome, <%= @user.username %></h2>
    <hr>
  </div>
  <div class="row">
    <% if current_user == @user %>
      <div class="col s2 m2">
        <%= button_to "Edit Profile", edit_user_path(@user), :method => :get, class:"btn btn-danger center-block" %>
      </div>
      <div class="col s2 m2">
        <%= button_to "Delete Profile", @user, class: "btn red", method: :delete, data: {confirm: "Are you sure you want to delete your profile?"} %>
      </div>
  </div>
  <div class="row">
    <h3>Get your expenses organized!</h3>
  </div>
    <div class="row">
      <div class="col s4 m4">
        <%= button_to "Add Transaction", new_user_entry_path(@user), method: :get, class:"btn" %>
      </div>
      <div class="col s4 m4">
        <%= button_to "View Transactions", user_entries_path(@user), method: :get, class:"btn" %>
      </div>
      <div class="col s4 m4">
        <%= button_to "Dashboard", dashboard_path, method: :get, class:"btn" %>
      </div>
    </div>
    <div class="row">
      <div class="col s4 m4">
        <%= button_to "View Categories", categories_path, method: :get, class:"btn" %>
      </div>
      <div class="col s4 m4">
        <%= button_to "Generate Report", reports_path, method: :get, class:"btn" %>
      </div>
    </div>
  <% end %>
</div>