config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'welcome#index', as: "root"

  resources :users do
    resources :entries
  end
  resources :categories
  # SESSION ROUTES
  get '/login' => 'sessions#new', as: 'login'
  get '/auth/:provider/callback' => 'sessions#create_with_facebook'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  # REPORTS ROUTE
  get '/reports' => 'reports#index', as: 'reports'
  # DASHBOARD ROUTE
  get '/dashboard' => 'dashboard#index', as: 'dashboard'



end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>XTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= javascript_include_tag 'application' %>
    <!--Import Google Fonts-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway|Sansita">
  </head>

  <body>
    <nav class="nav-color">
    <div class="nav-wrapper">
      <%= link_to root_path, class: "brand-logo logo" do %>
              <%= image_tag 'x.png', class:"logo" %>
            <% end %>
            <%= link_to root_path, class: "logo-name" do %>
              <span> xTracker</span>
            <% end %>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <% if current_user %>
        <li><%= link_to "Dashboard", dashboard_path %></li>
        <li><%= link_to "Reports", reports_path %></li>
        <li><%= link_to "Profile", user_path(current_user) %></li>
        <li><%= link_to "Log Out", logout_path %></li>

    <% else %>
        <li><%=link_to "Log In", login_path %></li>
        <li><%=link_to "Sign Up", new_user_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
  <% flash.each do |name, msg| %>
  <strong><%= msg %></strong>
  <% end %>
      <%= yield %>
  </body>
</html>